export enum Styles {
  RED = 'red-style',
  GREEN = 'green-style',
  BLUE = 'blue-style',
  YELLOW = 'yellow-style',
  PURPLE = 'purple-style',
  ACCELERATOR = 'accelerator-style',
  LIMITED = 'limited-style',
  DARK = 'dark-style',
  NUCLEAR = 'nuclear-style',
  GENERATOR_YELLOW_PURPLE = 'generator-yellow-purple-style',
  YELLOW_PURPLE = 'yellow-purple-style',
  RED_PURPLE = 'red-purple-style',
  RED_PURPLE_GENERATOR = 'red-purple-generator-style',
}
