export enum Styles {
  RED = 'red',
  YELLOW = 'yellow',
  SUB_RED = 'sub red',
  RED_AUTOMATOR = 'red automator',
  RED_UNLOCK = 'red unlock',
  RED_ACCELERATOR_UNLOCK = 'red red-accelerator unlock',
  RED_ACCELERATOR = 'red red-accelerator',
  RED_SUPER = 'red super',
  YELLOW_SUPER = 'yellow super',
  SUB_YELLOW = 'sub yellow',
  PROXIMA_CENTAURI = "yellow proxima-centauri",
  LALANDE = "yellow lalande",
  SUN = "yellow sun",
  SIRIUS = "yellow sirius",
  FUSION = "yellow fusion color-switch",
  HYDROGEN = "yellow hydrogen color-switch",
  FUSION_SUPER = "yellow fusion super color-switch",
  GREEN = "green",
  SUB_GREEN = "green sub",
  DARK = "green dark",
}
