import { BoosterAccelerationUpgrade } from './booster-acceleration-upgrade';
import {ElementCardEffects} from '../elements/blue-element';
import {Num} from '../../../num';

describe('BoosterAccelerationUpgrade', () => {
  it('should create an instance', () => {
    expect(new BoosterAccelerationUpgrade()).toBeTruthy();
  });

  it('includes free Booster Accelerations generated by Fluorine', () => {
    const upgrade = new BoosterAccelerationUpgrade('test-booster-acceleration');
    upgrade.amount = new Num(2, 0);
    ElementCardEffects.fluorineFreeBoosterAccelerations = new Num(1, 0);

    expect(upgrade.action().toNumber()).toBeCloseTo(.09, 10);
    expect(upgrade.totalFreeBuys.toNumber()).toBe(30);

    ElementCardEffects.reset();
  });
});
