import {Num} from "../../../num";

export const holdings = {
  redParticles: {amount: new Num(1, 2)},
  redParticlesStart: {amount: new Num(1, 2)},
  redAccelerators: {amount: new Num(1, 0)},
  redAcceleratorsStart: {amount: new Num(1, 0)},
  yellowParticles: {amount: new Num(0, 0)},
  yellows: {amount: new Num(0, 0)},
  yellowPower: {amount: new Num(0, 0)},
  yellowFusion: {amount: new Num(1, 0)},
  yellowFusionMax: {amount: new Num(1, 110)},
  yellowFusionPower: {amount: new Num(2, -1)},
  greenParticles: {amount: new Num(0, 0)},
  greens: {amount: new Num(0, 0)},
  greenEnergy: {amount: new Num(0, 0)},
  greenSouls: {amount: new Num(0, 0)},
  darkEnergy: {amount: new Num(0, 0)},
  darkEnergySubtract: {amount: new Num(0, 0)},
  darkAgeMax: {amount: new Num(1, 110)},
  darkPower: {amount: new Num(0, 0)},
  maxDarkPower: {amount: new Num(6.66, 2)},
  nuclearDecay: {amount: new Num(0, 0)},
  blueParticles: {amount: new Num(0, 0)},
  blues: {amount: new Num(0, 0)},
  blueNeutrons: {amount: new Num(0, 0)},
  blueLight: {amount: new Num(0, 0)},
  blueHydrogen: {amount: new Num(1, 0)},
  purples: {amount: new Num(0, 0)},
  purpleParticles: {amount: new Num(0, 0)},
  purpleVoid: {amount: new Num(1, 0)},
  redPurple: {amount: new Num(1, 0)},
  yellowPurple: {amount: new Num(1, 0)},
  greenPurple: {amount: new Num(1, 0)},
  bluePurple: {amount: new Num(1, 0)},
}
